[project]
name = "whisper-transcription"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper>=1.0.3",
    "requests==2.31.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
